### ISSUE TITLE
Can't attach images.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SolarLune/masterplan#11]
Steps to reproduce:
New Task > Change task Type: Image > Load.
pngs, gifs and jpgs are greyed out
MacOS Catalina 10.15.3 Beta (19D62e)
<img width="911" alt="Screen Shot 2020-02-02 at 12 16 03 PM" src="https://user-images.githubusercontent.com/23037821/73614653-06e11480-45b6-11ea-825d-c6fc6e38d4b6.png">

**Comment by SolarLune** [comment]
Yo! This is due to a bug in the package I use to open dialogs ([dlgs](https://github.com/gen2brain/dlgs/pull/13)); I've created a PR to resolve it on the repo, but in the meantime, I should be able to push out a build through itch that resolves this today. 

To build MasterPlan in the meantime without waiting for the PR to go through, you'd have to modify go.mod to point to a local folder with my fork of dlgs. I can add that information and advise that if the PR takes too long to go through, but for now I'd just suggest waiting.

**Comment by SolarLune** [comment]
That was merged, so this should be good to close now. Thanks!
