### ISSUE TITLE
License

### ISSUE THREAD

**Issue by muevoid** [SolarLune/masterplan#29]
Obviously this is your code and yours to do with as you please. But I am curious why you chose to make this proprietary since it has so little restrictions when building it yourself from what I understand. Of course you do not need to explain yourself however I was just curious.

**Comment by SolarLune** [comment]
Hello! 

Really sorry for the late reply to this! 

I chose to make it proprietary because I still want to actively sell the software. However, I do appreciate open source software and want to encourage developers to make interesting programs. It can be a great learning resource to see how bigger projects (if you want to call this one) work, and so I have the code available here for perusal and usage on GitHub.

**Comment by muevoid** [comment]
No worrires about the late response! One question though you could always have it be oss but still sell the binaries as you do right now many oss software does this. One example I can think of is the game mindustry. Either way I am satisfied with this response so you may close this whenever. Sorry if i came across as rude. Have a good day!

**Comment by SolarLune** [comment]
Hmm, this is something to consider, and I agree that a pure OSS software could be profitable / still sold. Thank you for the advice!

**Comment by dumblob** [comment]
I wonder whether the time has come to re-asses the decision to not make it OSS (yet)? Maybe not directly under a permissive license (MIT, BSD, ...) but at least some copyleft license (GPL, AGPL, ...)?

If not, it's fine. I really just want to know what to (not) recommend to the devs I know.

Basically I'm just curious as I myself don't plan to use Masterplan any time soon (I require a workflow which works as good on desktop as it does on mobile Android).
